site_name: Nextflow on AWS
nav:
- Introduction: index.md
- Modules:
  - 0 - Environment Setup: modules/module-0__sagemaker-environment.md
  - 1 - Running Nextflow: modules/module-1__running-nextflow.md
  - 2 - AWS Resources: modules/module-2__aws-resources.md

extra_css: [extra.css]
extra_javascript: [extra.js]

theme:
  name: material
  logo: 'images/AWS_logo_RGB_REV.svg'
  palette:
    primary: blue grey
    accent: deep orange

markdown_extensions:
  - admonition
  - codehilite