---
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  (WWPS-GWF-NEXTFLOW-CLOUD9) Creates a Cloud9 environment for developing genomics
  workflows using Nextflow

# Parameters:
#   EnvironmentOwnerIAMType:
#     Type: String
#     AllowedValues:
#       - user
#       - assumed-role
#     Default: assumed-role
#   EnvironmentOwnerIAMName:
#     Type: String
#     Default: TeamRole
#     Description: >-
#       IAM user name or assumed-role name that will be set as the environment owner.
#       Note: This cannot be "*"
  
Resources:
  IAMInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NextflowAdminInstanceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
  
  IAMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: NextflowAdminInstanceRole
      Roles:
        - Ref: IAMInstanceRole
  
  Cloud9Environment:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      Name: genomics-workflows
      Description: Development environment for building genomics workflows with Nextflow
      InstanceType: m4.large
      AutomaticStopTimeMinutes: 30
      # OwnerArn:
      #   Fn::Join:
      #     - ":"
      #     - - !Sub "arn:aws:iam::${AWS::AccountId}"
      #       - !Join ["/", [!Ref "EnvironmentOwnerIAMType", !Ref "EnvironmentOwnerIAMName"]]
      # Repositories:
      #   # despite the docs saying that this should be a CodeCommit repository
      #   # it seems to work with any publically accessible git repository with an HTTPS url
      #   - RepositoryUrl: https://github.com/wleepang/demo-genomics-workflows.git
      #     PathComponent: genomics-workflows

Outputs:
  Cloud9EnvironmentInstance:
    Value: !Join ["-", ["aws-cloud9", !GetAtt Cloud9Environment.Name, !Ref Cloud9Environment]]
    Description: >-
      EC2 Instance for AWS Cloud9 IDE used for workshop
    
  # Cloud9EnvironmentOwner:
  #   Value:
  #     Fn::Join:
  #       - ":"
  #       - - !Sub "arn:aws:iam::${AWS::AccountId}"
  #         - !Join ["/", [!Ref "EnvironmentOwnerIAMType", !Ref "EnvironmentOwnerIAMName"]]
  #   Description: >-
  #     ARN of the owner for the AWS Cloud9 IDE
      
  IAMInstanceProfile:
    Value: !GetAtt IAMInstanceProfile.Arn
    Description: >-
      Instance profile that needs to be manually associated with the AWS Cloud9 EC2 Instance.
...