---
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  (WWPS-GWF-NEXTFLOW-CLOUD9) Creates a Cloud9 environment for developing genomics
  workflows using Nextflow

Parameters:
  EnvironmentOwnerType:
    Type: String
    AllowedValues:
      - user
      - assumed-role
    Default: assumed-role
    Description: >-
      Type of access the owner of environment has.  The default is an assumed-role
      which is used by the workshop event engine.  If testing this in your own account this should
      be "user".
  EnvironmentOwnerName:
    Type: String
    Default: TeamRole/MasterKey
    Description: >-
      IAM user name or assumed-role name and session name that will be set as the environment owner.
      Note: This cannot be "*".  The default is "TeamRole/MasterKey" which is created by the 
      workshop event engine.  If testing this in your own account, you should set it to your IAM user name.

Conditions:
  UseAssumedRole:
    Fn::Equals:
      - !Ref EnvironmentOwnerType
      - assumed-role
  
Resources:
  IAMInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NextflowAdminInstanceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
  
  IAMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: NextflowAdminInstanceRole
      Roles:
        - Ref: IAMInstanceRole
  
  CodeCommitRepo:
    # This CodeCommit repository is for code that workshop participants will
    # interact with in Code9
    Type: AWS::CodeCommit::Repository
    Properties:
        RepositoryName: nextflow-workshop
        RepositoryDescription: >-
          Code for Nextflow on AWS workshop activities in Cloud9

        Code:
            S3:
              Bucket: pwyming-demo-templates
              Key: nextflow-workshop/cloud9.zip
  
  Cloud9Environment:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      Name: genomics-workflows
      Description: Development environment for building genomics workflows with Nextflow
      InstanceType: t2.medium
      OwnerArn:
        Fn::If:
          - UseAssumedRole
          - !Sub "arn:aws:sts::${AWS::AccountId}:assumed-role/${EnvironmentOwnerName}"
          - !Sub "arn:aws:iam::${AWS::AccountId}:user/${EnvironmentOwnerName}"
      
      Repositories:
        # despite the docs saying that this should be a CodeCommit repository
        # it seems to work with any publically accessible git repository with an HTTPS url
        - RepositoryUrl: !GetAtt CodeCommitRepo.CloneUrlHttp
          PathComponent: nextflow-workshop

Outputs:
  Cloud9EnvironmentInstance:
    Value: !Join ["-", ["aws-cloud9", !GetAtt Cloud9Environment.Name, !Ref Cloud9Environment]]
    Description: >-
      EC2 Instance for AWS Cloud9 IDE used for workshop
        
  IAMInstanceProfile:
    Value: !GetAtt IAMInstanceProfile.Arn
    Description: >-
      Instance profile that needs to be manually associated with the AWS Cloud9 EC2 Instance.
...